### ISSUE TITLE
Compatibility issues with industrialcraft mods

### ISSUE THREAD

**Issue by iconFehu** [PorPit/UltimateStack#16]
Currently known issues
industrialcraft-2-2.8.197-ex112.jar
UltimateStack-1.12.2-1.3.1.jar
At the same time running on version 1.12.2 there will be problems

**Comment by iconFehu** [comment]
This is the environment where I run and the startup log information

[14:47:09] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:47:09] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[14:47:09] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[14:47:09] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[14:47:09] [main/INFO]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[14:47:09] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_181, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_181
[14:47:10] [main/INFO]: Searching C:\Minecraft\.minecraft\versions\1.12.2-mods\mods for mods
[14:47:10] [main/INFO]: Searching C:\Minecraft\.minecraft\versions\1.12.2-mods\mods\1.12.2 for mods
[14:47:10] [main/INFO]: Loading tweaker codechicken.asm.internal.Tweaker from ChickenASM-1.12-1.0.2.7.jar
[14:47:10] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in UltimateStack-1.12.2-1.3.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[14:47:10] [main/WARN]: The coremod UltimateStackPatchingLoader (com.porpit.ultimatestack.transform.UltimateStackPatchingLoader) is not signed!
[14:47:10] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[14:47:10] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[14:47:10] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[14:47:10] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ClassTransformer
[14:47:10] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:242]: OptiFine ZIP file: C:\Minecraft\.minecraft\libraries\optifine\OptiFine\1.12.2_HD_U_F5\OptiFine-1.12.2_HD_U_F5-installer.jar
[14:47:10] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:47:10] [main/INFO]: Loading tweak class name codechicken.asm.internal.Tweaker
[14:47:10] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[14:47:10] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:47:10] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[14:47:10] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:47:12] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[14:47:12] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[14:47:12] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:47:12] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[14:47:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: com/porpit/ultimatestack/transform/UltimateStackTransformer
[14:47:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.porpit.ultimatestack.transform.UltimateStackPatchingLoader.getASMTransformerClass(UltimateStackPatchingLoader.java:16)
[14:47:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129)
[14:47:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:139)
[14:47:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
[14:47:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: com.porpit.ultimatestack.transform.UltimateStackTransformer
[14:47:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:185)
[14:47:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14:47:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14:47:12] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 4 more
[14:47:12] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoClassDefFoundError: com/porpit/ppcore/transform/PPCoreTransformer
[14:47:12] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[14:47:12] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[14:47:12] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[14:47:12] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
[14:47:12] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 6 more
[14:47:12] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: com.porpit.ppcore.transform.PPCoreTransformer
[14:47:12] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:97)
[14:47:12] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14:47:12] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14:47:12] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 10 more
Exception in thread "main"

**Comment by PorPit** [comment]
I'll check this issues later ~ I'm remaking this mod using Mixin

**Comment by PorPit** [comment]
fixed
