### ISSUE TITLE
使用模组崩溃无法启动游戏

### ISSUE THREAD

**Issue by XiaowuAiMC** [PorPit/UltimateStack#5]
Phosphor 与 终极堆叠 模组

以下为未启动游戏崩溃
----------------------------------------------------------------------------------------------------------
[18:53:17] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:53:17] [main/INFO]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[18:53:17] [main/INFO]: Loading tweak class name optifine.OptiFineForgeTweaker
[18:53:17] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[18:53:17] [main/INFO]: Forge Mod Loader version 14.23.5.2838 for Minecraft 1.12.2 loading
[18:53:17] [main/INFO]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_211, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_211
[18:53:18] [main/INFO]: Searching D:\1.12.2整合\.minecraft\versions\1.12.2\mods for mods
[18:53:18] [main/INFO]: Searching D:\1.12.2整合\.minecraft\versions\1.12.2\mods\1.12.2 for mods
[18:53:18] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from spongeforge-1.12.2-2838-7.1.7-RC3777.jar
[18:53:18] [main/WARN]: Found FMLCorePluginContainsFMLMod marker in UltimateStack-1.12.2-1.3.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:53:18] [main/WARN]: The coremod UltimateStackPatchingLoader (com.porpit.ultimatestack.transform.UltimateStackPatchingLoader) is not signed!
[18:53:18] [main/INFO]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from phosphor-1.12.2-0.2.4+build46-universal.jar
[18:53:18] [main/INFO]: Calling tweak class optifine.OptiFineForgeTweaker
[18:53:18] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: acceptOptions
[18:53:18] [main/INFO]: [optifine.OptiFineForgeTweaker:dbg:56]: OptiFineForgeTweaker: injectIntoClassLoader
[18:53:18] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ClassTransformer
[18:53:18] [main/INFO]: [optifine.OptiFineClassTransformer:dbg:221]: OptiFine ZIP file: D:\1.12.2整合\.minecraft\libraries\optifine\OptiFine\1.12.2_HD_U_E4_pre4\OptiFine-1.12.2_HD_U_E4_pre4.jar
[18:53:18] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:53:18] [main/INFO]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[18:53:18] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.7.11 Source=file:/D:/1.12.2整合/.minecraft/versions/1.12.2/mods/spongeforge-1.12.2-2838-7.1.7-RC3777.jar Service=LaunchWrapper Env=CLIENT
[18:53:18] [main/DEBUG]: Instantiating coremod class SpongeCoremod
[18:53:18] [main/DEBUG]: The coremod org.spongepowered.mod.SpongeCoremod requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[18:53:18] [main/WARN]: The coremod SpongeCoremod (org.spongepowered.mod.SpongeCoremod) is not signed!
[18:53:18] [main/INFO]: Compatibility level set to JAVA_8
[18:53:18] [main/INFO]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[DEFAULT]
[18:53:18] [main/INFO]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[PREINIT]
[18:53:18] [main/INFO]: Adding new token provider org.spongepowered.mod.SpongeCoremod$TokenProvider to MixinEnvironment[INIT]
[18:53:18] [main/DEBUG]: Added access transformer class org.spongepowered.mod.asm.transformer.SpongeAccessTransformer to enqueued access transformers
[18:53:18] [main/DEBUG]: Enqueued coremod SpongeCoremod
[18:53:19] [main/DEBUG]: Instantiating coremod class PhosphorFMLLoadingPlugin
[18:53:19] [main/DEBUG]: The coremod me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin requested minecraft version 1.12.2 and minecraft is 1.12.2. It will be loaded.
[18:53:19] [main/DEBUG]: Found signing certificates for coremod PhosphorFMLLoadingPlugin (me.jellysquid.mods.phosphor.core.PhosphorFMLLoadingPlugin)
[18:53:19] [main/DEBUG]: Found certificate f0387d288626cc2d937daa504e74af570c52a2f1
[18:53:19] [main/DEBUG]: Enqueued coremod PhosphorFMLLoadingPlugin
[18:53:19] [main/WARN]: Tweak class name org.spongepowered.asm.launch.MixinTweaker has already been visited -- skipping
[18:53:19] [main/INFO]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:53:19] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:53:19] [main/INFO]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:53:19] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:53:19] [main/DEBUG]: Injecting coremod FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\} class transformers
[18:53:19] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
[18:53:19] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
[18:53:19] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
[18:53:19] [main/TRACE]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SoundEngineFixTransformer
[18:53:19] [main/DEBUG]: Injection complete
[18:53:19] [main/DEBUG]: Running coremod plugin for FMLCorePlugin \{net.minecraftforge.fml.relauncher.FMLCorePlugin\}
[18:53:19] [main/DEBUG]: Running coremod plugin FMLCorePlugin
[18:53:23] [main/INFO]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[18:53:23] [main/INFO]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
[18:53:23] [main/DEBUG]: Coremod plugin class FMLCorePlugin run successfully
[18:53:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:53:23] [main/DEBUG]: Injecting coremod FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\} class transformers
[18:53:23] [main/DEBUG]: Injection complete
[18:53:23] [main/DEBUG]: Running coremod plugin for FMLForgePlugin \{net.minecraftforge.classloading.FMLForgePlugin\}
[18:53:23] [main/DEBUG]: Running coremod plugin FMLForgePlugin
[18:53:23] [main/DEBUG]: Coremod plugin class FMLForgePlugin run successfully
[18:53:23] [main/INFO]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:53:23] [main/DEBUG]: Injecting coremod UltimateStackPatchingLoader \{com.porpit.ultimatestack.transform.UltimateStackPatchingLoader\} class transformers
[18:53:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: com/porpit/ultimatestack/transform/UltimateStackTransformer
[18:53:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at com.porpit.ultimatestack.transform.UltimateStackPatchingLoader.getASMTransformerClass(UltimateStackPatchingLoader.java:16)
[18:53:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:129)
[18:53:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[18:53:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[18:53:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: com.porpit.ultimatestack.transform.UltimateStackTransformer
[18:53:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[18:53:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[18:53:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[18:53:23] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 4 more
[18:53:23] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NoClassDefFoundError: com/porpit/ppcore/transform/PPCoreTransformer
[18:53:23] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[18:53:23] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[18:53:23] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[18:53:23] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[18:53:23] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 6 more
[18:53:23] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: com.porpit.ppcore.transform.PPCoreTransformer
[18:53:23] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
[18:53:23] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[18:53:23] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[18:53:23] [main/INFO]: [java.lang.Throwable:printStackTrace:-1]: 	... 10 more

**Comment by XiaowuAiMC** [comment]
游戏版本:1.12.2 forge-1.12.2-14.23.5.2838 模组版本:1.3.1

**Comment by XiaowuAiMC** [comment]
我电脑配置渣，所以装点优化模组，但是就遇到问题

**Comment by PorPit** [comment]
发下你所有mod 的列表 以及 前置版本

**Comment by XiaowuAiMC** [comment]
Phosphor无前置

**Comment by PorPit** [comment]
> Phosphor无前置

PPCore的版本号是多少,   还有就是这个mod  (Phosphor)如果删掉能正常启动吗

**Comment by XiaowuAiMC** [comment]
我好像知道了，没有装前置就会崩溃
